### ISSUE TITLE
Crashing, Tried 5-7 times.

### ISSUE THREAD

**Issue by yeroc5311** [etianl/Trouser-Streak#41]
I have little to no clue on what is causing a crash. If i have to (or you ask me to), I will send this issue to the Meteor Client page. Here is the crash: 
Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_239.method_17783()" because "this.field_4015.field_1765" is null
at net.minecraft.class_757.handler$bbf000$meteor-client$onUpdateTargetedEntity(class_757.java:2690)
at net.minecraft.class_757.method_3190(class_757.java:634)
at net.minecraft.class_757.method_3188(class_757.java:1050)
at net.minecraft.class_757.method_3192(class_757.java:858)
at net.minecraft.class_310.method_1523(class_310.java:1320)
at net.minecraft.class_310.method_1514(class_310.java:888)
at net.minecraft.client.main.Main.main(Main.java:265)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I tried joining a server twice, and a singleplayer world 3 times *(i think...)*

**Comment by etianl** [comment]
When does the crash occur? I need details to try to reproduce it. Thanks

**Comment by yeroc5311** [comment]
I checked my meteor client files and found out it was a weird config issue. I (accidentally) fixed it myself.
